bar:
  location: top
  monitor: eDP-1
  
  height: 20
  spacing: 2
  margin: 5
  
  font: Fixed:pixelsize=18:weight=bold

  background: 2D353Bff
  foreground: D3C6AAff  

  border:
    bottom-width: 2
    color: D3C6AAff
#######################################
  left:
    - i3:
        sort: native
        spacing: 4
        content:
          "":
            map:
              conditions:
                state == urgent:
                  string: 
                    text: " {name} "
                    on-click: "swaymsg --quiet workspace {name}"
                    foreground: E67E80ff
                state == focused:
                  string: 
                    text: "[{name}]"
                    on-click: "swaymsg --quiet workspace {name}"
                    foreground: 2D353Bff
                    deco:
                      background:
                        color: D3C6AAff
                state == unfocused:
                  string: 
                    text: " {name} "
                    on-click: "swaymsg --quiet workspace {name}"
                state == invisible:
                  string: 
                    text: " {name} "
                    on-click: "swaymsg --quiet workspace {name}"
#######################################
  right:
    - script:
        path: "/usr/local/bin/power.sh"
        args:
          - "bar"
        content:
          list:
            items:
              - string:
                  text: "MODE:"
              - map:
                  conditions:
                    ppd == power-saver:
                      string:
                        text: "POWER SAVE"
                        foreground: A7C080ff
                    ppd == balanced:
                      string:
                        text: "NORMAL"
                        foreground: DBBC7Fff
                    ppd == performance:
                      string:
                        text: "PERFORMANCE"
                        foreground: D699B6ff
            on-click:
              left: "power.sh bal"
              wheel-up: "power.sh per"
              wheel-down: "power.sh sav"
    - label:
        content:
          string:
            text: "|"
    - cpu:
        poll-interval: 1000
        content:
          map:
            conditions:
              id < 0:
                list:
                  items:
                    - string:
                        text: "CPU:"
                    - map:
                        conditions:
                          cpu < 1:
                            string:
                              text: "1"
                              foreground: A7C080ff
                          cpu < 10:
                            string:
                              text: "{cpu}"
                              foreground: A7C080ff
                          cpu < 80:
                            string:
                              text: "{cpu}"
                              foreground: DBBC7Fff
                          cpu < 101:
                            string:
                              text: "{cpu}"
                              foreground: E67E80ff
                    - string:
                        text: "%"
    - mem:
        poll-interval: 1000
        content:
          list:
            items:
              - string:
                  text: "MEM:"
              - map:
                  conditions:
                    percent_used < 25:
                      string:
                        text: "{percent_used}"
                        foreground: A7C080ff
                    percent_used < 90:
                      string:
                        text: "{percent_used}"
                        foreground: DBBC7Fff
                    percent_used < 101:
                      string:
                        text: "{percent_used}"
                        foreground: E67E80ff
              - string:
                  text: "%"
    - label:
        content:
          string:
            text: "|"
    - pipewire:
        content:
          map:
            conditions:
              type == "sink":
                map: 
                  conditions:
                    ~muted:
                      string:
                        text: "{description},{cubic_volume}%"
                        on-click:
                          left: "vol.sh mute"
                          middle: "pavucontrol"
                          wheel-up: "vol.sh up"
                          wheel-down: "vol.sh down"
                    muted:
                      string:
                        text: "{description},MUTED"
                        foreground: E67E80ff
                        on-click:
                          left: "vol.sh mute"
                          middle: "pavucontrol"
    - label:
        content:
          string:
            text: "|"
    - battery:
        name: BAT0
        poll-interval: 10000
        content:
          list: 
            items:
              - string:
                  text: "BAT:"
              - map:
                  conditions:
                    capacity < 20:
                      string:
                        text: "{capacity}"
                        foreground: E67E80ff
                    capacity < 50:
                      string:
                        text: "{capacity}"
                        foreground: DBBC7Fff
                    capacity < 100:
                      string:
                        text: "{capacity}"
                        foreground: A7C080ff
                    capacity == 100:
                      string:
                        text: "{capacity}"
                        foreground: 7FBBB3ff
              - map:
                  conditions:
                    state == full:
                      string:
                        text: "%,FULL"
                    state == charging:
                      string:
                        text: "%,CHARGING"
                    state == discharging:
                      string:
                        text: "%,TR:{estimate}"
    - label:
        content:
          string:
            text: "|"
    - clock:
        date-format: "D:%d,M:%m"
        content:
          string:
            text: "{date}"
    - label:
        content:
          string:
            text: "|"
    - clock:
        time-format: "%H:%M"
        content:
          string:
            text: "{time}"
            foreground: 9DA9A0ff
