[charger]
# see available governors by running: 
# cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors
governor = performance

# EPP: see available preferences by running: 
# cat /sys/devices/system/cpu/cpu0/cpufreq/energy_performance_available_preferences
energy_performance_preference = performance

# EPB (Energy Performance Bias) for the intel_pstate driver
# see conversion info: https://www.kernel.org/doc/html/latest/admin-guide/pm/intel_epb.html
# available EPB options include a numeric value between 0-15
# (where 0 = maximum performance and 15 = maximum power saving),
# or one of the following strings:
# performance (0), balance_performance (4), default (6), balance_power (8), or power (15)
# the default value is `balance_performance` (for charger)
energy_perf_bias = 0

# Platform Profiles
# https://www.kernel.org/doc/html/latest/userspace-api/sysfs-platform_profile.html
# See available options by running:
# cat /sys/firmware/acpi/platform_profile_choices
platform_profile = cool

# minimum cpu frequency (in kHz)
scaling_min_freq = 1000000

# maximum cpu frequency (in kHz)
scaling_max_freq = 5000000

# turbo boost setting. possible values: always, auto, never
turbo = always


# this is for ignoring controllers and other connected devices battery from affecting 
# laptop preformence
# [power_supply_ignore_list]

# name1 = this
# name2 = is
# name3 = an
# name4 = example


[battery]
# Specify which battery device to use for reading battery information. see available batteries by running: ls /sys/class/power_supply/
# If not set, auto-cpufreq will automatically detect and use the first battery found
battery_device = BAT0

# see available governors by running: cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors
# preferred governor
governor = powersave

# EPP: see available preferences by running: 
# cat /sys/devices/system/cpu/cpu0/cpufreq/energy_performance_available_preferences
energy_performance_preference = power

# EPB (Energy Performance Bias) for the intel_pstate driver
# see conversion info: https://www.kernel.org/doc/html/latest/admin-guide/pm/intel_epb.html
# available EPB options include a numeric value between 0-15
# (where 0 = maximum performance and 15 = maximum power saving),
# or one of the following strings:
# performance (0), balance_performance (4), default (6), balance_power (8), or power (15)
# the default value is `balance_power` (for battery)
energy_perf_bias = 15

# Platform Profiles
# https://www.kernel.org/doc/html/latest/userspace-api/sysfs-platform_profile.html
# See available options by running:
# cat /sys/firmware/acpi/platform_profile_choices
platform_profile = quiet

# minimum cpu frequency (in kHz)
scaling_min_freq = 800000

# maximum cpu frequency (in kHz)
scaling_max_freq = 1500000

# turbo boost setting. possible values: always, auto, never
turbo = never
